# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainGUIfile(object):
    def setupUi(self, mainGUIfile):
        mainGUIfile.setObjectName("mainGUIfile")
        mainGUIfile.resize(683, 384)
        self.label = QtWidgets.QLabel(mainGUIfile)
        self.label.setGeometry(QtCore.QRect(0, 0, 683, 384))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/008c1ec6621b132d42af32394fde1611.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.text_Day = QtWidgets.QTextBrowser(mainGUIfile)
        self.text_Day.setGeometry(QtCore.QRect(510, 85, 131, 21))
        self.text_Day.setStyleSheet("background-color:Transparent;\n"
"border-radius:none;\n"
"")
        self.text_Day.setObjectName("text_Day")
        self.text_Date = QtWidgets.QTextBrowser(mainGUIfile)
        self.text_Date.setGeometry(QtCore.QRect(510, 135, 131, 21))
        self.text_Date.setStyleSheet("background-color:Transparent;\n"
"border-radius:none;\n"
"")
        self.text_Date.setObjectName("text_Date")
        self.text_Time = QtWidgets.QTextBrowser(mainGUIfile)
        self.text_Time.setGeometry(QtCore.QRect(500, 180, 131, 21))
        self.text_Time.setStyleSheet("background-color:Transparent;\n"
"border-radius:none;\n"
"")
        self.text_Time.setObjectName("text_Time")
        self.text_Terminal = QtWidgets.QTextBrowser(mainGUIfile)
        self.text_Terminal.setGeometry(QtCore.QRect(440, 240, 211, 111))
        self.text_Terminal.setStyleSheet("background-color:Transparent;\n"
"border-radius:none;\n"
"")
        self.text_Terminal.setObjectName("text_Terminal")
        self.pushButton_Start = QtWidgets.QPushButton(mainGUIfile)
        self.pushButton_Start.setGeometry(QtCore.QRect(7, 165, 151, 71))
        self.pushButton_Start.setMinimumSize(QtCore.QSize(151, 0))
        self.pushButton_Start.setStyleSheet("background-color:Transparent;\n"
"font: 12pt \"Avengeance\";\n"
"color: rgb(0, 255, 255);\n"
"border-radius:none;\n"
"\n"
"")
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.pushButton = QtWidgets.QPushButton(mainGUIfile)
        self.pushButton.setGeometry(QtCore.QRect(97, 165, 151, 71))
        self.pushButton.setStyleSheet("background-color:Transparent;\n"
"font: 12pt \"Avengeance\";\n"
"color: rgb(0, 255, 255);\n"
"border-radius:none;\n"
"\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(mainGUIfile)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 91, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Downloads/—Pngtree—minimalistic line blue futuristic technology_4020916.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(mainGUIfile)
        self.label_3.setGeometry(QtCore.QRect(130, 160, 91, 81))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Downloads/—Pngtree—minimalistic line blue futuristic technology_4020916.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(mainGUIfile)
        self.label_4.setGeometry(QtCore.QRect(260, 80, 201, 201))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Downloads/XDZT.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(mainGUIfile)
        QtCore.QMetaObject.connectSlotsByName(mainGUIfile)

    def retranslateUi(self, mainGUIfile):
        _translate = QtCore.QCoreApplication.translate
        mainGUIfile.setWindowTitle(_translate("mainGUIfile", "mainGUIfile"))
        self.pushButton_Start.setText(_translate("mainGUIfile", "Start"))
        self.pushButton.setText(_translate("mainGUIfile", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainGUIfile = QtWidgets.QWidget()
    ui = Ui_mainGUIfile()
    ui.setupUi(mainGUIfile)
    mainGUIfile.show()
    sys.exit(app.exec_())
